/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.qlsvapp.ui;

import com.mycompany.qlsvapp.helper.DataValidator;
import com.mycompany.qlsvapp.helper.MessageDialog;
import com.mycompany.qlsvapp.model.NguoiDung;
import com.mycompany.qlsvapp.model.dao.NguoiDungDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tuan Tien
 */
public class Admin extends javax.swing.JPanel {
    private MainForm parentForm;
    private DefaultTableModel tblModel;
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        
        initTable();
        
        loadDataToTable();
    }
    private void initTable(){
        tblModel = new DefaultTableModel();
        tblModel.setColumnIdentifiers(new String[]{"Tên đăng nhập", "Mật khẩu", "Quyền"});
        tblUser.setModel(tblModel);
    }
    
    private void loadDataToTable(){
        try {
            NguoiDungDao dao = new NguoiDungDao();
            List<NguoiDung> list = dao.findAll();
            tblModel.setRowCount(0);
            for(NguoiDung it: list){
                tblModel.addRow(new Object[]{
                    it.getTenDangNhap(), it.getMatKhau(), it.getQuyen()
                });
            }
            tblModel.fireTableDataChanged();
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtQuyen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnNhapmoi = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        txtTaikhoan = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        txtQuyen.setText("Giảng viên");

        jLabel3.setText("Mật khẩu");

        jLabel4.setText("Quyền");

        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlsvapp/icons/Save-icon.png"))); // NOI18N
        btnadd.setText("Thêm");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlsvapp/icons/Actions-document-edit-icon-16.png"))); // NOI18N
        btnupdate.setText("Sửa");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlsvapp/icons/Button-Close-icon-16.png"))); // NOI18N
        btndelete.setText("Xóa");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnNhapmoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/qlsvapp/icons/new-icon-16.png"))); // NOI18N
        btnNhapmoi.setText("Nhập mới");
        btnNhapmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhapmoiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản Lý User");

        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblUser);

        jLabel2.setText("Tài khoản");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnadd)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnupdate)
                                        .addGap(18, 18, 18)
                                        .addComponent(btndelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnNhapmoi))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtQuyen, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                        .addComponent(txtpassword, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtTaikhoan, javax.swing.GroupLayout.Alignment.LEADING)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnadd)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btnNhapmoi))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtTaikhoan, sb, "Tên đăng nhập không được để trống");
        DataValidator.validateEmpty(txtpassword, sb, "Password không được để trống");
        DataValidator.validateEmpty(txtQuyen, sb, "Quyền không được để trống");
        if (sb.length()>0) {
            MessageDialog.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        try {
            NguoiDung nd = new NguoiDung();
            nd.setTenDangNhap(txtTaikhoan.getText());
            nd.setMatKhau(txtpassword.getText());
            nd.setQuyen(txtQuyen.getText());

            NguoiDungDao dao = new NguoiDungDao();
            if (dao.findById(txtTaikhoan.getText()) != null) {
                MessageDialog.showErrorDialog(parentForm, "Trùng tên tài khoản", "Cảnh báo");
            }else{
                if (dao.insert(nd)) {
                    MessageDialog.showMessageDialog(parentForm, "Người dùng thêm thành công", "Thông báo");
                    loadDataToTable();
                }else{
                    MessageDialog.showErrorDialog(parentForm, "Người dùng thêm thất bại", "Cảnh báo");
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtTaikhoan, sb, "Tên tài khoản không được để trống");
        DataValidator.validateEmpty(txtpassword, sb, "Password không được để trống");
        if (sb.length()>0) {
            MessageDialog.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if (MessageDialog.showConfirmDialog(parentForm,
            "Bạn có muốn cập nhật người dùng không ?", "Hỏi")== JOptionPane.NO_OPTION){
        return;
        }
        try {
            NguoiDung nd = new NguoiDung();
            nd.setTenDangNhap(txtTaikhoan.getText());
            nd.setMatKhau(txtpassword.getText());
            nd.setQuyen(txtQuyen.getText());

            NguoiDungDao dao = new NguoiDungDao();
            if (dao.update(nd)) {
                MessageDialog.showMessageDialog(parentForm, "Người dùng đã được cập nhật", "Thông báo");
                loadDataToTable();
            }else{
                MessageDialog.showErrorDialog(parentForm, "Người dùng chưa được cập nhật", "Cảnh báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        StringBuilder sb = new StringBuilder();
        DataValidator.validateEmpty(txtTaikhoan, sb, "Tên đăng nhập không được để trống");
        if (sb.length()>0) {
            MessageDialog.showErrorDialog(parentForm, sb.toString(), "Lỗi");
            return;
        }
        if (MessageDialog.showConfirmDialog(parentForm,
            "Bạn có muốn xóa người dùng không ?", "Hỏi")== JOptionPane.NO_OPTION){
        return;
        }
        try {
            NguoiDungDao dao = new NguoiDungDao();
            if (dao.deleteUser(txtTaikhoan.getText())) {
                MessageDialog.showMessageDialog(parentForm, "Người dùng đã được xóa", "Thông báo");
                btnNhapmoiActionPerformed(evt);
                loadDataToTable();
            }else{
                MessageDialog.showErrorDialog(parentForm, "Người dùng chưa được xóa", "Cảnh báo");
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnNhapmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhapmoiActionPerformed
        txtTaikhoan.setText("");
        txtpassword.setText("");
    }//GEN-LAST:event_btnNhapmoiActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        try {
            int row = tblUser.getSelectedRow();

            if(row >= 0){
                String id = (String) tblUser.getValueAt(row, 0);
                NguoiDungDao dao = new NguoiDungDao();
                NguoiDung nd = dao.findById(id);
                if(nd != null){
                    txtTaikhoan.setText(nd.getTenDangNhap());
                    txtpassword.setText(nd.getMatKhau());
                    txtQuyen.setText(nd.getQuyen());
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            MessageDialog.showErrorDialog(parentForm, e.getMessage(), "Lỗi");
        }
    }//GEN-LAST:event_tblUserMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNhapmoi;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable tblUser;
    private javax.swing.JTextField txtQuyen;
    private javax.swing.JTextField txtTaikhoan;
    private javax.swing.JTextField txtpassword;
    // End of variables declaration//GEN-END:variables
}
